name: Build Package and Push

on:
  release:
    types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pip3 install --user --upgrade pipenv && pipenv install --dev --python 3.8
        shell: bash

      - name: bump_version
        run: |
          echo "[INFO] Get latest tag"
          git fetch --all --tags
          RELEASE_VERSION=$(git tag | tail -1)
          RELEASE_VERSION=$(echo $RELEASE_VERSION | sed s/v//)
          echo $RELEASE_VERSION

          echo "[INFO] Get current version"
          CURRENT_VERSION=$(cat $INIT_FILE | grep "__version__" | grep -oP "([0-9]*\.[0-9]*\.[0-9]*)")
          echo $CURRENT_VERSION

          echo "[INFO] Bump version"
          sed -i s/$CURRENT_VERSION/$RELEASE_VERSION/ $INIT_FILE

          echo "[INFO] Commit and push"
          git config user.name $GIT_USERNAME
          git config user.email $GIT_EMAIL
          git add $INIT_FILE
          git commit -m "Bump version from $CURRENT_VERSION to $RELEASE_VERSION"
        env:
          INIT_FILE: leverage/__init__.py
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

      - name: clean
        run: |
          rm -rf ./build/ &&	rm -rf ./dist/

      - name: build
        run: |
          pipenv run python setup.py sdist bdist_wheel

      - name: check
        run:
          pipenv run twine check dist/*

      - name: upload
        run: |
          pipenv run twine upload --non-interactive --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: commit_push
        run: |
          git push

      - uses: act10ns/slack@v1
        if: always()
        with: 
          status: ${{ job.status }}
          channel: $SLACK_CI_CHANNEL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CI_CHANNEL: ${{ secrets.SLACK_CI_CHANNEL }}
