name: Test Build Package and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          "Version to publish (optional):
          If not given, next patch from latest will be used."
        default: ""
        required: false

jobs:
  build_push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: install_dependencies
        run: |
          pip3 install --user --upgrade pipenv && pipenv install --dev --python 3.8
        shell: bash

      - name: bump_version
        run: |
          echo "[INFO] Get current version"
          CURRENT_VERSION=$(cat $INIT_FILE | grep "__version__" | grep -oP "([0-9]*\.[0-9]*\.[0-9]*)")
          echo $CURRENT_VERSION

          [ -z "$RELEASE_VERSION" ] && \
            LATEST_VERSION=$(curl -sL "https://test.pypi.org/pypi/leverage/json" | jq ".releases | keys | sort | .[-1]") && \
            RELEASE_VERSION=$(echo ${LATEST_VERSION:1:-1} | awk 'BEGIN{FS="."; OFS="."} {print $1,$2,$3+1}')

          echo "[INFO] Bump version to $RELEASE_VERSION"
          sed -i s/$CURRENT_VERSION/$RELEASE_VERSION/ $INIT_FILE
        env:
          INIT_FILE: leverage/__init__.py
          RELEASE_VERSION: ${{ github.event.inputs.version }}

      - name: clean
        run: |
          rm -rf ./build/ &&	rm -rf ./dist/

      - name: build
        run: |
          pipenv run python setup.py sdist bdist_wheel

      - name: check
        run:
          pipenv run twine check dist/*

      - name: upload
        run: |
          pipenv run twine upload --non-interactive --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
